### PR TITLE
Configurable default units

### PR DESCRIPTION
**Pull request by jeffmcmahan**
See https://github.com/jsstyles/jss/issues/271

**SUMMARY**
1. Delete numericProps.js.
1. Add defaultProps.js (a map of props to default units).
1. Change index.js to lookup defaults.
1. Change index.js to use the options parameter differently.
1. Added tests for `ms` and `%` units.
1. Added test for configured properties.
1. Changed tests using the property name 'property' to a real property ('background-size').

**BREAKING CHANGES**
There are at least two breaking changes; they don't much affect real life, but it's worth knowing what they are:

1. Setting the options object to something like `{unit: 'em'}` no longer changes all units.
1. Properties containing 'origin' (except for `mask-origin`) now get `%` as a default unit.

We could change the code to avoid (1) and (2), but in the case of (1), the options API becomes logically less predictable and less understandable if we make 'unit' into a super setting that overrides all others. In the case of (2), keeping to `px` makes the default setting less useful in general (I would argue).

### CODE REVIEW

**Comment by jeffmcmahan** [comment]
Actually, it just occurred to me that this will change any value that *can* take a px unit to px. That means properties like `line-height` will default to `px` instead of being numeric. I think it'd be best if I edit the list so that doesn't happen.

**Comment by kof** [comment]
Yeah, numeric props by default should stay numeric.  This is pretty much the list we have right now, except of the last one recently added property.

**Comment by kof** [comment]
Oh however this list could be shortened because it needs to contain only props which would accept also px, there are some which accept numerics only anyways.

**Comment by jeffmcmahan** [comment]
New map appears below. There are 4 properties are set to 'ms', 4 are set to '%', and the rest are 'px'. No properties that will accept a plain numeric value appear in the map below - only those which require a unit.

The code that generates the map is [here](https://gist.github.com/jeffmcmahan/4cc8e57d826cac71d582928a910a4954) (gist). 

```js
/**
 * Generated jss-default-unit CSS property units
 * @object
 */
export default {
  'background-position-x': 'px',
  'background-position-y': 'px',
  'background-size': 'px',
  border: 'px',
  'border-bottom': 'px',
  'border-bottom-left-radius': 'px',
  'border-bottom-right-radius': 'px',
  'border-bottom-width': 'px',
  'border-left': 'px',
  'border-left-width': 'px',
  'border-radius': 'px',
  'border-right': 'px',
  'border-right-width': 'px',
  'border-spacing': 'px',
  'border-top': 'px',
  'border-top-left-radius': 'px',
  'border-top-right-radius': 'px',
  'border-top-width': 'px',
  'border-width': 'px',
  bottom: 'px',
  'column-gap': 'px',
  'column-rule': 'px',
  'column-rule-width': 'px',
  'column-width': 'px',
  'flex-basis': 'px',
  'font-size': 'px',
  height: 'px',
  left: 'px',
  'letter-spacing': 'px',
  margin: 'px',
  'margin-bottom': 'px',
  'margin-left': 'px',
  'margin-right': 'px',
  'margin-top': 'px',
  'max-height': 'px',
  'max-width': 'px',
  'min-height': 'px',
  'min-width': 'px',
  motion: 'px',
  'motion-offset': 'px',
  outline: 'px',
  'outline-offset': 'px',
  'outline-width': 'px',
  padding: 'px',
  'padding-bottom': 'px',
  'padding-left': 'px',
  'padding-right': 'px',
  'padding-top': 'px',
  perspective: 'px',
  right: 'px',
  'shape-margin': 'px',
  size: 'px',
  'text-indent': 'px',
  top: 'px',
  'vertical-align': 'px',
  'border-after-width': 'px',
  'border-before-width': 'px',
  'border-end-width': 'px',
  'border-horizontal-spacing': 'px',
  'border-start-width': 'px',
  'border-vertical-spacing': 'px',
  'font-size-delta': 'px',
  'logical-height': 'px',
  'logical-width': 'px',
  'margin-after': 'px',
  'margin-before': 'px',
  'margin-end': 'px',
  'margin-start': 'px',
  'mask-position-x': 'px',
  'mask-position-y': 'px',
  'mask-size': 'px',
  'max-logical-height': 'px',
  'max-logical-width': 'px',
  'min-logical-height': 'px',
  'min-logical-width': 'px',
  'padding-after': 'px',
  'padding-before': 'px',
  'padding-end': 'px',
  'padding-start': 'px',
  'perspective-origin-x': '%',
  'perspective-origin-y': '%',
  'text-stroke': 'px',
  'text-stroke-width': 'px',
  'transform-origin-x': '%',
  'transform-origin-y': '%',
  'transform-origin-z': 'px',
  width: 'px',
  'word-spacing': 'px',
  'animation-delay': 'ms',
  'animation-duration': 'ms',
  'transition-delay': 'ms',
  'transition-duration': 'ms'
}
```

**Comment by kof** [comment]
We can generate this map at runtime once and cache, so there is literally no perf overhead. However we would need a static map for ssr.

**Comment by kof** [comment]
I did it for vendor prefixer plugin same way.

**Comment by jeffmcmahan** [comment]
My code works by iterating the CSS properties of a DOM node to set them to various value types and then check whether Chrome permits the assigned type. Sadly, other vendors' DOM APIs don't allow that. In FireFox `HTMLElement.style` is neither iterable nor serializable (`CSS2Properties` instance).

Since some vendors are unwilling to allow iterating the properties, I think it'd be best to use a static list instead of trying to hack our way to a complete list in every browser.

What do you think?

**Comment by kof** [comment]
https://github.com/jsstyles/css-vendor/blob/master/src/supported-property.js#L20

**Comment by kof** [comment]
Actually it is optional there, so i don't even know if the cache is prefilled in firefox, forgot the details of implementation.

**Comment by jeffmcmahan** [comment]
I used .getComputedStyle, but results are inconsistent among browsers (Chome/FF). The core cases are the same, but some shorthand properties (e.g., `border`) are not. This'd result in our assigning different default units in different browsers. That would be just about impossible to anticipate and probably very frustrating to debug. 

Chrome is very well behaved. It does the right thing in every case. FireFox doesn't. I still recommend including the list generated by Chrome.

**Comment by kof** [comment]
yep

**Comment by jeffmcmahan** [comment]
All set.

**Comment by jeffmcmahan** [comment]
Let me know if there are further issues with this PR that I should be working on.

**Comment by kof** [comment]
Just wanted to merge it, but there is a conflict

**Comment by kof** [comment]
can you resolve or should I?

**Comment by jeffmcmahan** [comment]
Okay, but once merged, ignoreProps.js needs to be deleted. For some reason, its being deleted in my fork manifests as a merge conflict, so I un-deleted it, as it were.

**Pull request merged**
